version: 2
jobs:
  release-vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - run: apt-get install -y libssl-dev
      - checkout
      - run: make test config=release

  debug-vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - run: apt-get install -y libssl-dev
      - checkout
      - run: make test config=debug

  release-vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - run: apt-get install -y libssl-dev
      - checkout
      - run: make test config=release

  debug-vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - run: apt-get install -y libssl-dev
      - checkout
      - run: make test config=debug

workflows:
  version: 2
  commit:
    jobs:
      - release-vs-ponyc-release
      - debug-vs-ponyc-release
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - release-vs-ponyc-master
      - debug-vs-ponyc-master
