version: 2.1

orbs:
  zulip: ponylang/zulip@1

jobs:
  release-vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: bash .ci-scripts/install-openssl-0.9.8.bash
      - run: make test config=release ssl=0.9.0
      - zulip/status:
          fail_only: true

  debug-vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: bash .ci-scripts/install-openssl-0.9.8.bash
      - run: make test config=debug ssl=0.9.0
      - zulip/status:
          fail_only: true

  release-vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: bash .ci-scripts/install-openssl-0.9.8.bash
      - run: make test config=release ssl=0.9.0
      - zulip/status:
          fail_only: true

  debug-vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: bash .ci-scripts/install-openssl-0.9.8.bash
      - run: make test config=debug ssl=0.9.0
      - zulip/status:
          fail_only: true

  verify-changelog:
    docker:
      - image: ponylang/changelog-tool:release
    steps:
      - checkout
      - run: changelog-tool verify
      - zulip/status:
          fail_only: true

workflows:
  version: 2.1
  commit:
    jobs:
      - verify-changelog:
          context: org-global
      - release-vs-ponyc-release:
          context: org-global
      - debug-vs-ponyc-release:
          context: org-global

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - release-vs-ponyc-master:
          context: org-global

      - debug-vs-ponyc-master:
          context: org-global
