version: 2.1

orbs:
  zulip: ponylang/zulip@1.0.0

jobs:
  release-vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - run: apt-get update
      - run: apt-get -y install curl
      - checkout
      - run: bash .ci-scripts/install-openssl-0.9.8.bash
      - run: make test config=release
      - zulip/status:
          fail_only: true

  debug-vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - run: apt-get update
      - run: apt-get -y install curl
      - checkout
      - run: bash .ci-scripts/install-openssl-0.9.8.bash
      - run: make test config=debug
      - zulip/status:
          fail_only: true

  release-vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: bash .ci-scripts/install-openssl-0.9.8.bash
      - run: make test config=release
      - zulip/status:
          fail_only: true

  debug-vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: bash .ci-scripts/install-openssl-0.9.8.bash
      - run: make test config=debug
      - zulip/status:
          fail_only: true

workflows:
  version: 2.1
  commit:
    jobs:
      - release-vs-ponyc-release:
          context: org-global

      - debug-vs-ponyc-release:
          context: org-global

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - release-vs-ponyc-master:
          context: org-global

      - debug-vs-ponyc-master:
          context: org-global
